query GetAdminByUsername($_username: String!) {
  admin(where: {username: {_eq: $_username}}) {
    id
    password
  }
}
query GetAdminById($id: uuid = "") {
  admin_by_pk(id: $id) {
    id
    username
  }
}
mutation insertAdmin($password: String = "", $username: String = "") {
  insert_admin_one(object: {password: $password, username: $username}) {
    id
  }
}
